name: Awesome API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  AZURE_WEBAPP_PACKAGE_PATH: 'Awesome APIs/Net5Superpowers.WebUI/'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '5.0.x'           # set this to the dot net version to use
  NODE_VERSION: '14.x'           # set this to the node version to use


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: |
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        dotnet restore
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal
