name: Awesome API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  AZURE_WEBAPP_NAME: dotnet5-todos    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'Awesome APIs/Net5Superpowers.WebUI/'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '5.0.x'           # set this to the dot net version to use
  NODE_VERSION: '14.x'           # set this to the node version to use


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: |
        cd "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
        dotnet restore
        dotnet build --configuration Release
        dotnet test --no-build --verbosity normal
        dotnet publish -c Release -o './myapp' 

    - if: ${{ github.event_name != 'pull_request' }}
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    # Deploy to Azure Web apps
    - if: ${{ github.event_name != 'pull_request' }}
      name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
    
    - if: ${{ github.event_name != 'pull_request' }}
      name: logout
      run: |
        az logout
